### ISSUE TITLE
Use gender-neutral collective noun

### ISSUE THREAD

**Issue by lbeaufort** [FlaskCon/website#14]
👋 thanks for open-sourcing the flaskcon website!

It would be more inclusive to use a gender-neutral collective noun, as opposed to ["guys"](https://github.com/FlaskCon/website/search?q=guys&unscoped_q=guys). The alternative "coders" was suggested on Twitter. I'm happy to put in a pull request unless someone else is interested. 

Here's a helpful reference: https://youguys.club/
>For decades, _guys_ has been used to address a mixed group of men and women. It’s increasingly viewed as a gender neutral plural.
>
>But the singular _guy_ still has a strongly male inflection. Consider _that guy_, or the 
_Python guy_. Do those sound like women? Not likely.
>
>Even today when a group of guys may be entirely female, it still can have a sexist, male-as-default ring to it.
>
> **What should I say instead?**
> There are a [lot of options](http://www.chicagonow.com/listing-beyond-forty/2017/05/40-gender-neutral-alternatives-to-saying-you-guys/).
>
> _Y’all_ is a fabulous all-purpose pronoun. It’s great even if you’re not a Southerner!
>
> _Are y’all going to join youguys.club?_
>
> _Hey gang_ works well as a casual option.
>
> _Hi folks_ is a little more formal, but too folksy for some. _Everyone_ sounds great with any audience.
> 
> Addressing the group by a label can also help, whether it’s _hi team_ or _hey friends_.
> 
> _Hey team, let’s finish those TPS reports._
> 

Thanks again!

**Comment by Abdur-rahmaanJ** [comment]
@lbeaufort would you like to be assigned the issue?

**Comment by lbeaufort** [comment]
@Abdur-rahmaanJ I'd be happy to make the change, thank you!

**Comment by Abdur-rahmaanJ** [comment]
Missed the PR part, it's now ok. You can go ahead 👍
