### ISSUE TITLE
Page layout

### ISSUE THREAD

**Issue by joshuap233** [FlaskCon/website#16]
Hello, the page seems a little mess,so i change the page layout

New page:

![1](https://user-images.githubusercontent.com/47631325/85512449-7ec6de80-b62c-11ea-9048-06682f7edadb.png)

[source](https://github.com/pjshu/website)

I'm not sure my layout is appropriate, so I use React to write this page(i new in Jquery,so 

,I didn't modify the source code directly)

**Comment by Abdur-rahmaanJ** [comment]
@pjshu great!!! just see the existing codebase and try to implement it!

**Comment by kouul** [comment]
Thanks @pjshu. 
I like the design. It's neat and smooth. But since it's for Flaskcon, it made more sense to use Flask (: So i will just wait for some other organizing members to check first.

I'd like to point out one thing on the countdown, based on the screenshot you shared, is it 10 days 109 hours 227 minutes 445 seconds?

**Comment by joshuap233** [comment]
> @pjshu great!!! just see the existing codebase and try to implement it!

thanks, i  add some note to my code,
source code:
https://github.com/pjshu/website/tree/master/src/components
https://github.com/pjshu/website/blob/master/src/App.js

**Comment by joshuap233** [comment]
> Thanks @pjshu.
> I like the design. It's neat and smooth. But since it's for Flaskcon, it made more sense to use Flask (: So i will just wait for some other organizing members to check first.
> 
> I'd like to point out one thing on the countdown, based on the screenshot you shared, is it 10 days 109 hours 227 minutes 445 seconds?

thanks,The problem has been fixed

**Comment by Abdur-rahmaanJ** [comment]
@pjshu see the current design if ok!

**Comment by joshuap233** [comment]
> @pjshu see the current design if ok!
great
