### ISSUE TITLE
Assets Reinit

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [FlaskCon/website#26]
@greyli i think i messed with the commits, your reviewers pic got washed away, could you look into it? Thanks!

**Comment by greyli** [comment]
Got it, I will fix it.

**Comment by greyli** [comment]
[Fixed](https://github.com/FlaskCon/website/commit/b3ccd0b965a851072b935436e0193b0b15ba42de). You just need to run `python statictipy.py --no-server` after changed the template.

**Comment by Abdur-rahmaanJ** [comment]
Weird running it without `--no-server` should have the same effect but don't know why. Thank You!
