### ISSUE TITLE
Clarify schedule time format

### ISSUE THREAD

**Issue by greyli** [FlaskCon/website#27]
I notice the `GMT` is removed on session time, but I got confused about it. What time the Sessionize API returned? What time the website displayed? GMT or user's local time? It will be better to convert the time to the user's timezone if possible.

**Comment by Abdur-rahmaanJ** [comment]
@greyli see the mail i cced you. Apparently it gets displayed to the speaker's timezone but now checking no ... i guess we must readd GMT

**Comment by greyli** [comment]
OK, I'm gonna re-add the `GMT` first, then try to support timezone convert based on the user's timezone.
